name: bakebudget_pastry_office_185t
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.2
  uuid: ^4.5.1
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  intl: ^0.20.2
  flutter_bloc: ^9.1.0
  fl_chart: ^0.70.2
  apphud: ^2.6.0
  path_provider: ^2.1.5
  in_app_review: ^2.0.8
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SF Compact Rounded
      fonts:
        - asset: assets/fonts/SF-Compact-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Compact-Rounded-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-Compact-Rounded-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Compact-Rounded-Bold.ttf
          weight: 700
